import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/app/context/CartContext";
import { ImageProvider } from "@/app/context/ImageContext";
import { DarkModeProvider } from "@/app/context/DarkModeContext";
import { AuthProvider } from "@/app/context/AuthContext";
import ThemeProvider from "@/app/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100`}
      >
        <CartProvider>
          <ImageProvider>
            <DarkModeProvider>
              <ThemeProvider>
                <AuthProvider>{children}</AuthProvider>
              </ThemeProvider>
            </DarkModeProvider>
          </ImageProvider>
        </CartProvider>
      </body>
    </html>
  );
}
