import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ImageProvider } from "../../src/app/context/ImageContext";
import { CartProvider } from "../../src/app/context/CartContext";

// app/layout.tsx (ejemplo)
import { DarkModeProvider } from "../../src/app/context/DarkModeContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <ImageProvider>
          <DarkModeProvider>{children}</DarkModeProvider>
          </ImageProvider>
        </CartProvider>
      </body>
    </html>
  );
}
